### ISSUE TITLE
image loading problem

### ISSUE THREAD

**Issue by nushrathumaira** [Vipoooool/Keras-Model-Deployment-Using-Django#3]
When I run the server and choose an image from the filebrowser, predict gives following error.

Internal Server Error: /
Traceback (most recent call last):
  File "/home/..../myenv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/....../myenv/lib/python3.7/site-packages/django/core/handlers/base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/...../Keras-Model-Deployment-Using-Django/plant_diseases_recognition_app/views.py", line 62, in prediction
    img = image.load_img(myfile, target_size=(224, 224))
  File "/home/...../myenv/lib/python3.7/site-packages/tensorflow/python/keras/preprocessing/image.py", line 301, in load_img
    target_size=target_size, interpolation=interpolation)
  File "/home/..../myenv/lib/python3.7/site-packages/keras_preprocessing/image/utils.py", line 113, in load_img
    with open(path, 'rb') as f:
TypeError: expected str, bytes or os.PathLike object, not InMemoryUploadedFile

I haven't made any changes to the code

**Comment by Ali-Kamel** [comment]
any one solved this yet ?
